# netlify.toml

[build]
  publish = "dist"
  command = "npm run compile"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

[[headers]]
  for = "/**/*"
  [headers.values]
    cache-control = '''
      max-age=31536000,
      no-cache'''